"""Append-only V3.6 runner for the fixed 224-slot schedule.

All outputs remain under the private V3.6 run root.  The runner never writes a
submission, reads platform data, or overwrites a completed trial.
"""
from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
import hashlib
import json
from pathlib import Path
import subprocess
import time
from typing import Any, Mapping, Sequence

import numpy as np
import pandas as pd

from .data import TARGETS
from .v3_1_search import trial_identity
from .v3_4_bags import protocol_bag_hash
from .v3_5_run import v35_trial_identity
from .v3_6_models import evaluate_v36_outer_folds
from .v3_6_sampler import load_v36_config, sample_v36
from .v3_run import load_fold_vector, load_training_frame

_WORKER_TRAIN: pd.DataFrame | None = None
_WORKER_FOLDS: np.ndarray | None = None


def _init_worker(train: pd.DataFrame, folds: np.ndarray) -> None:
    global _WORKER_TRAIN, _WORKER_FOLDS
    _WORKER_TRAIN, _WORKER_FOLDS = train, folds


def _worker_run(payload: dict) -> dict:
    if _WORKER_TRAIN is None or _WORKER_FOLDS is None:
        raise RuntimeError("V3.6 worker was not initialised")
    result = evaluate_v36_outer_folds(
        _WORKER_TRAIN, _WORKER_FOLDS, payload["trial"], fold_ids=tuple(payload["fold_ids"])
    )
    return {"trial": payload["trial"], "identity": payload["identity"], **result}


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _hash_frame(frame: pd.DataFrame) -> str:
    digest = hashlib.sha256()
    for value in frame["sample_id"].astype(str).tolist():
        digest.update(value.encode("utf-8"))
        digest.update(b"\x00")
    values = np.ascontiguousarray(frame[[*frame.columns[2:]]].select_dtypes(include=[np.number]).to_numpy(dtype=float))
    digest.update(values.tobytes())
    return digest.hexdigest()


def _hash_folds(folds: np.ndarray, fold_ids: Sequence[int]) -> str:
    digest = hashlib.sha256()
    digest.update(np.asarray(folds, dtype=np.int64).tobytes())
    digest.update(",".join(str(int(v)) for v in fold_ids).encode("ascii"))
    return digest.hexdigest()


def _source_files(root: Path) -> list[Path]:
    files = [
        root / "configs/round2_v3_6/search.yaml",
        root / "src/bf_tap_r2/v3_6_sampler.py",
        root / "src/bf_tap_r2/v3_6_models.py",
        root / "src/bf_tap_r2/v3_6_networks.py",
        root / "src/bf_tap_r2/v3_6_reference.py",
        root / "src/bf_tap_r2/v3_6_run.py",
    ]
    return [path for path in files if path.exists()]


def _code_version(root: Path) -> str:
    digest = hashlib.sha256()
    for path in sorted(_source_files(root), key=lambda p: str(p)):
        digest.update(path.read_bytes())
    try:
        head = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=root, text=True).strip()
    except Exception:
        head = "no-git-head"
    return f"{head}:{digest.hexdigest()}"


def _known_events(ledger: Path) -> set[tuple[str, str]]:
    if not ledger.exists():
        return set()
    known: set[tuple[str, str]] = set()
    for line in ledger.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        event = json.loads(line)
        known.add((str(event.get("event")), str(event.get("trial_id"))))
    return known


def _completed(ledger: Path) -> dict[str, dict]:
    out: dict[str, dict] = {}
    if not ledger.exists():
        return out
    for line in ledger.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        event = json.loads(line)
        if event.get("event") == "complete":
            out[str(event["trial_id"])] = event
    return out


def _bag_hash_for_trial(trial: Mapping[str, Any], train: pd.DataFrame) -> str | None:
    kind = str(trial.get("kind"))
    if kind.startswith("ebm"):
        params = dict(trial.get("parameters", {}))
        protocol = dict(trial.get("protocol", {}))
        if "outer_bags" not in params:
            parent_id = str(trial.get("parent_trial_id", ""))
            # O/D trials generated by the sampler always carry outer_bags.
            raise ValueError(f"V3.6 EBM trial {trial.get('trial_id')} lacks outer_bags ({parent_id})")
        return protocol_bag_hash(
            train,
            n_outer_bags=int(params.get("outer_bags", 4)),
            n_inner_splits=int(protocol.get("inner_splits", 5)),
            seed=int(protocol.get("bag_seed", params.get("random_state", 42))),
        )
    return None


def _identity_matches(stored: Mapping[str, Any], desired: Mapping[str, Any]) -> bool:
    return json.dumps(stored, sort_keys=True, default=str) == json.dumps(desired, sort_keys=True, default=str)


def _private_output(root: Path, output: Path) -> None:
    private = (root / "local/runs/round2-v3.6-loss-training-and-numeric-encoding").resolve()
    if not output.resolve().is_relative_to(private):
        raise ValueError(
            "V3.6 output must remain private under "
            "local/runs/round2-v3.6-loss-training-and-numeric-encoding"
        )


def _trial_identity(trial: Mapping[str, Any], *, stage: str, fold_seed: int, data_hash: str,
                    fold_hash: str, fold_ids: Sequence[int], code_version: str,
                    source_hash: str, bag_hash: str | None) -> dict:
    base = v35_trial_identity(
        trial,
        batch_id=f"v36-{stage}-seed{fold_seed}",
        data_hash=data_hash,
        fold_hash=fold_hash,
        fold_ids=tuple(fold_ids),
        model_seed=int(fold_seed),
        stage=stage,
        code_version=code_version,
        source_hash=source_hash,
        bag_hash=bag_hash,
    )
    base["version"] = "round2-v3.6-loss-training-and-numeric-encoding"
    base["training_protocol"] = (
        "numeric-network-train-fold-only-v1"
        if str(trial.get("kind", "")).startswith("numeric")
        else "ebm-group-safe-bags-v1"
    )
    return base


def _select_trials(trials: Sequence[dict], *, lines: Sequence[str] | None,
                   trial_ids: Sequence[str] | None, limit: int | None) -> list[dict]:
    selected = list(trials)
    if lines:
        wanted = {str(value) for value in lines}
        selected = [trial for trial in selected if str(trial.get("line")) in wanted]
    if trial_ids:
        wanted_ids = {str(value) for value in trial_ids}
        selected = [trial for trial in selected if str(trial.get("trial_id")) in wanted_ids]
    if limit is not None:
        selected = selected[: max(0, int(limit))]
    return selected


def run_batch(root: Path, output: Path, *, stage: str, fold_seed: int,
              fold_ids: Sequence[int], workers: int = 16, limit: int | None = None,
              line: str | None = None, trial_ids: Sequence[str] | None = None) -> dict:
    _private_output(root, output)
    output.mkdir(parents=True, exist_ok=True)
    config = load_v36_config(root)
    trials = _select_trials(
        sample_v36(root), lines=(line,) if line else None, trial_ids=trial_ids, limit=limit
    )
    if not trials:
        raise ValueError("No V3.6 trials selected")
    train = load_training_frame(root)
    folds = load_fold_vector(root, train, int(fold_seed))
    data_hash = _hash_frame(train)
    fold_hash = _hash_folds(folds, tuple(fold_ids))
    code_version = _code_version(root)
    source_hash = _sha256_bytes(code_version.encode("utf-8"))
    ledger = output / "fit_ledger.jsonl"
    completed = _completed(ledger)
    known = _known_events(ledger)
    pending: list[dict] = []
    identities: dict[str, dict] = {}
    for trial in trials:
        status = str(trial.get("status", "available"))
        if status == "not_applicable":
            if ("not_applicable", str(trial["trial_id"])) not in known:
                with ledger.open("a", encoding="utf-8") as handle:
                    handle.write(json.dumps({
                        "event": "not_applicable",
                        "trial_id": str(trial["trial_id"]),
                        "line": str(trial.get("line")),
                        "target": str(trial.get("target")),
                        "reason": str(trial.get("reason", "")),
                    }, ensure_ascii=False) + "\n")
            continue
        try:
            bag_hash = _bag_hash_for_trial(trial, train)
        except Exception as exc:  # noqa: BLE001 - preserve schedule error as evidence
            identity = {
                "trial_id": str(trial.get("trial_id")),
                "line": str(trial.get("line")),
                "error": f"{type(exc).__name__}: {exc}",
            }
            if ("failed", str(trial["trial_id"])) not in known:
                with ledger.open("a", encoding="utf-8") as handle:
                    handle.write(json.dumps({
                        "event": "failed",
                        "trial_id": str(trial["trial_id"]),
                        "line": str(trial.get("line")),
                        "target": str(trial.get("target")),
                        "identity": identity,
                        "error_type": type(exc).__name__,
                        "error": str(exc),
                        "time": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    }, ensure_ascii=False) + "\n")
            continue
        identity = _trial_identity(
            trial,
            stage=stage,
            fold_seed=int(fold_seed),
            data_hash=data_hash,
            fold_hash=fold_hash,
            fold_ids=tuple(fold_ids),
            code_version=code_version,
            source_hash=source_hash,
            bag_hash=bag_hash,
        )
        identities[str(trial["trial_id"])] = identity
        old = completed.get(str(trial["trial_id"]))
        if old is not None:
            if not _identity_matches(old.get("identity", {}), identity):
                raise ValueError(f"V3.6 cache identity mismatch: {trial['trial_id']}")
            continue
        pending.append(trial)
    batch_manifest = {
        "version": config["version"],
        "stage": stage,
        "fold_seed": int(fold_seed),
        "fold_ids": [int(v) for v in fold_ids],
        "data_hash": data_hash,
        "fold_hash": fold_hash,
        "code_version": code_version,
        "source_hash": source_hash,
        "slots_selected": len(trials),
        "pending_at_start": len(pending),
        "agent_uploads": 0,
    }
    (output / "batch.json").write_text(
        json.dumps(batch_manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    results: list[dict] = []
    if pending:
        payloads = [
            {"trial": trial, "identity": identities[str(trial["trial_id"])], "fold_ids": [int(v) for v in fold_ids]}
            for trial in pending
        ]
        with ProcessPoolExecutor(
            max_workers=max(1, int(workers)), initializer=_init_worker, initargs=(train, folds)
        ) as executor:
            futures = {executor.submit(_worker_run, payload): payload for payload in payloads}
            for future in as_completed(futures):
                payload = futures[future]
                trial = payload["trial"]
                try:
                    result = future.result()
                except Exception as exc:  # noqa: BLE001 - preserve failure evidence
                    with ledger.open("a", encoding="utf-8") as handle:
                        handle.write(json.dumps({
                            "event": "failed",
                            "trial_id": str(trial["trial_id"]),
                            "identity": payload["identity"],
                            "line": str(trial.get("line")),
                            "target": str(trial.get("target")),
                            "error_type": type(exc).__name__,
                            "error": str(exc),
                            "time": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                        }, ensure_ascii=False) + "\n")
                    continue
                prediction = np.asarray(result.pop("predictions"), dtype=float)
                np.save(output / f"pred-{trial['trial_id']}.npy", prediction)
                record = {
                    "event": "complete",
                    "trial_id": str(trial["trial_id"]),
                    "identity": result["identity"],
                    "target": str(trial["target"]),
                    "line": str(trial.get("line")),
                    "kind": str(trial["kind"]),
                    "status": str(trial.get("status", "available")),
                    "pooled_wmape": result["pooled_wmape"],
                    "mean_wmape": result["mean_wmape"],
                    "fold_scores": result["fold_scores"],
                    "fit_meta": result["fit_meta"],
                    "trial": trial,
                    "agent_uploads": 0,
                }
                with ledger.open("a", encoding="utf-8") as handle:
                    handle.write(json.dumps(record, ensure_ascii=False, default=str) + "\n")
                results.append(record)
                print(json.dumps({
                    "trial_id": str(trial["trial_id"]),
                    "line": str(trial.get("line")),
                    "target": str(trial["target"]),
                    "pooled_wmape": result["pooled_wmape"],
                }, ensure_ascii=False), flush=True)
    return {
        "status": "complete",
        "stage": stage,
        "slots_selected": len(trials),
        "pending_at_start": len(pending),
        "completed_this_run": len(results),
        "already_complete": sum(1 for trial in trials if str(trial["trial_id"]) in completed),
        "fold_seed": int(fold_seed),
        "fold_ids": [int(v) for v in fold_ids],
        "workers": int(workers),
        "agent_uploads": 0,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--workers", type=int, default=16)
    parser.add_argument("--fold-seed", type=int, default=42)
    parser.add_argument("--fold-ids", type=int, nargs="+", default=[0, 1])
    parser.add_argument("--line", choices=("O", "D", "N"), default=None)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--trial-id", action="append", default=None)
    args = parser.parse_args(argv)
    summary = run_batch(
        Path.cwd(),
        args.output,
        stage=f"fixed-{args.line or 'all'}",
        fold_seed=int(args.fold_seed),
        fold_ids=tuple(int(v) for v in args.fold_ids),
        workers=int(args.workers),
        limit=args.limit,
        line=args.line,
        trial_ids=args.trial_id,
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
