"""V4.2 S line: constrained symbolic regression over short expressions.

Evidence basis: the PySR documentation (https://pysr.ai/v1.5.9/options), which
supports configurable operators, complexity/depth constraints, custom losses and
NumPy export.

This round does **not** assume that the real data was generated by a
recoverable formula.  The only hypothesis under test is whether a constrained
short nonlinear expression can learn a more effective combination of the
current inputs than the existing models.  Nothing here is described as a real
blast-furnace mechanism or as recovery of an official generator.

Two backends exist:

* the in-repo bounded AST search, whose evaluation counter is exact and whose
  per-training-subset cap is enforced and recorded;
* an optional PySR adapter that is only used when the installed backend is
  verified to accept and report an exact evaluation budget.

Operator sets (per target):

===== ====================================================
ID    operator set
===== ====================================================
S0    ``+``, ``-``, ``*``  (short polynomial control)
S1    S0 + ``safe_ratio(a, b) = a / (1 + b * b)``
S2    S0 + ``tanh(a)``, ``log1p(abs(a))``
S3    union of S1 and S2
===== ====================================================

Constraints: at most 24 nodes and depth 5; nonlinear unary operators may not
self-nest; ``safe_ratio`` may not self-nest.  There is no arbitrary exponent,
no bare division, no ``sin``/``cos`` and no large conditional branch.
"""
from __future__ import annotations

import json
import math
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Mapping, Sequence

import numpy as np
import pandas as pd

from .data import FEATURES
from .metrics import wmape
from .v4_2_prep import (
    TargetScaler,
    fit_row_id_hash,
    group_hash,
    exclusion_group_keys,
    inner_uh_split,
    transform_hash,
)
from .v4_2_train import SYMBOLIC_LOSS, FitTimer, TrainConfig, TrainOutcome

__all__ = [
    "S_LIMITS",
    "S_RECIPES",
    "BoundedExpressionRegressor",
    "SymbolicLimits",
    "SymbolicSpec",
    "pysr_backend_report",
    "s_recipe_spec",
]

S_RECIPES: dict[str, dict[str, Any]] = {
    "S0": {"recipe_id": "S0", "operators": ("add", "sub", "mul"),
           "role": "short_polynomial_control"},
    "S1": {"recipe_id": "S1", "operators": ("add", "sub", "mul", "safe_ratio"),
           "role": "S0_plus_safe_ratio"},
    "S2": {"recipe_id": "S2", "operators": ("add", "sub", "mul", "tanh", "log1p_abs"),
           "role": "S0_plus_bounded_unary"},
    "S3": {"recipe_id": "S3",
           "operators": ("add", "sub", "mul", "safe_ratio", "tanh", "log1p_abs"),
           "role": "union_of_S1_and_S2"},
}

BINARY_OPERATORS = ("add", "sub", "mul", "safe_ratio")
UNARY_OPERATORS = ("tanh", "log1p_abs")

#: Pre-registered search budget.  ``eval_budget`` is an *upper* limit on
#: expression evaluations per training subset; the in-repo backend counts every
#: evaluation exactly and records the realised count and stop reason.
S_LIMITS: dict[str, Any] = {
    "max_nodes": 24,
    "max_depth": 5,
    "eval_budget": 200_000,
    "max_candidates": 12,
    "beam_width": 48,
    "no_improve_rounds": 4,
    "const_seeds": (0.5, 1.0, 2.0),
    "constant_refit_max_nfev": 400,
    "constant_bound": 100.0,
}


def s_recipe_spec(recipe_id: str) -> dict[str, Any]:
    key = str(recipe_id).upper()
    if key not in S_RECIPES:
        raise ValueError(f"Unknown S recipe: {recipe_id!r}")
    return deepcopy(S_RECIPES[key])


class SymbolicLimits:
    """Validated, explicit search budget; nothing is silently ignored."""

    def __init__(self, overrides: Mapping[str, Any] | None = None) -> None:
        unknown = sorted(set(overrides or {}) - set(S_LIMITS))
        if unknown:
            raise ValueError(f"Unknown S limit overrides: {unknown}")
        merged = dict(S_LIMITS)
        merged.update({str(k): v for k, v in (overrides or {}).items()})
        self.max_nodes = int(merged["max_nodes"])
        self.max_depth = int(merged["max_depth"])
        self.eval_budget = int(merged["eval_budget"])
        self.max_candidates = int(merged["max_candidates"])
        self.beam_width = int(merged["beam_width"])
        self.no_improve_rounds = int(merged["no_improve_rounds"])
        self.const_seeds = tuple(float(v) for v in merged["const_seeds"])
        self.constant_refit_max_nfev = int(merged["constant_refit_max_nfev"])
        self.constant_bound = float(merged["constant_bound"])
        if min(self.max_nodes, self.max_depth, self.eval_budget, self.max_candidates,
               self.beam_width, self.no_improve_rounds) <= 0:
            raise ValueError("Invalid S search limits")
        if self.max_nodes < 5:
            raise ValueError("S max_nodes must leave room for the affine head")

    def as_dict(self) -> dict[str, Any]:
        return {
            "max_nodes": int(self.max_nodes),
            "max_depth": int(self.max_depth),
            "eval_budget": int(self.eval_budget),
            "max_candidates": int(self.max_candidates),
            "beam_width": int(self.beam_width),
            "no_improve_rounds": int(self.no_improve_rounds),
            "const_seeds": list(self.const_seeds),
            "constant_refit_max_nfev": int(self.constant_refit_max_nfev),
            "constant_bound": float(self.constant_bound),
            "budget_kind": "exact_expression_evaluation_counter",
        }


class SymbolicSpec:
    def __init__(self, recipe_id: str) -> None:
        payload = s_recipe_spec(recipe_id)
        self.recipe_id = str(payload["recipe_id"])
        self.operators = tuple(str(v) for v in payload["operators"])
        self.role = str(payload["role"])
        for name in self.operators:
            if name not in {*BINARY_OPERATORS, *UNARY_OPERATORS}:
                raise ValueError(f"Unknown symbolic operator: {name!r}")

    def as_dict(self) -> dict[str, Any]:
        return {
            "recipe_id": self.recipe_id,
            "operators": list(self.operators),
            "role": self.role,
            "binary_operators": [n for n in self.operators if n in BINARY_OPERATORS],
            "unary_operators": [n for n in self.operators if n in UNARY_OPERATORS],
            "forbidden": ["bare_division", "power", "sin", "cos", "conditionals"],
        }


# ---------------------------------------------------------------------------
# AST
# ---------------------------------------------------------------------------
Node = tuple


def node_count(ast: Node) -> int:
    kind = ast[0]
    if kind in {"var", "const"}:
        return 1
    if kind in UNARY_OPERATORS:
        return 1 + node_count(ast[1])
    return 1 + node_count(ast[1]) + node_count(ast[2])


def node_depth(ast: Node) -> int:
    kind = ast[0]
    if kind in {"var", "const"}:
        return 1
    if kind in UNARY_OPERATORS:
        return 1 + node_depth(ast[1])
    return 1 + max(node_depth(ast[1]), node_depth(ast[2]))


def _contains(ast: Node, kinds: frozenset[str]) -> bool:
    kind = ast[0]
    if kind in kinds:
        return True
    if kind in {"var", "const"}:
        return False
    if kind in UNARY_OPERATORS:
        return _contains(ast[1], kinds)
    return _contains(ast[1], kinds) or _contains(ast[2], kinds)


NONLINEAR_UNARY = frozenset({"tanh", "log1p_abs"})


def ast_to_string(ast: Node, names: Sequence[str]) -> str:
    kind = ast[0]
    if kind == "var":
        return str(names[int(ast[1])])
    if kind == "const":
        return f"{float(ast[1]):.12g}"
    if kind == "add":
        return f"({ast_to_string(ast[1], names)} + {ast_to_string(ast[2], names)})"
    if kind == "sub":
        return f"({ast_to_string(ast[1], names)} - {ast_to_string(ast[2], names)})"
    if kind == "mul":
        return f"({ast_to_string(ast[1], names)} * {ast_to_string(ast[2], names)})"
    if kind == "safe_ratio":
        left = ast_to_string(ast[1], names)
        right = ast_to_string(ast[2], names)
        return f"({left} / (1 + {right} * {right}))"
    if kind == "tanh":
        return f"tanh({ast_to_string(ast[1], names)})"
    if kind == "log1p_abs":
        return f"log1p(|{ast_to_string(ast[1], names)}|)"
    raise ValueError(f"Unknown AST node: {kind!r}")


def _evaluate(ast: Node, x: np.ndarray) -> np.ndarray:
    """Evaluate an AST on the encoded design matrix ``x`` (n, p)."""
    kind = ast[0]
    if kind == "var":
        return x[:, int(ast[1])]
    if kind == "const":
        return np.full(x.shape[0], float(ast[1]), dtype=np.float64)
    if kind == "add":
        return _evaluate(ast[1], x) + _evaluate(ast[2], x)
    if kind == "sub":
        return _evaluate(ast[1], x) - _evaluate(ast[2], x)
    if kind == "mul":
        return _evaluate(ast[1], x) * _evaluate(ast[2], x)
    if kind == "safe_ratio":
        left = _evaluate(ast[1], x)
        right = _evaluate(ast[2], x)
        return left / (1.0 + right * right)
    if kind == "tanh":
        return np.tanh(_evaluate(ast[1], x))
    if kind == "log1p_abs":
        return np.log1p(np.abs(_evaluate(ast[1], x)))
    raise ValueError(f"Unknown AST node: {kind!r}")


def _replace_constants(ast: Node, values: np.ndarray, cursor: list[int]) -> Node:
    kind = ast[0]
    if kind == "const":
        index = cursor[0]
        cursor[0] += 1
        return ("const", float(values[index]))
    if kind == "var":
        return ast
    if kind in UNARY_OPERATORS:
        return (kind, _replace_constants(ast[1], values, cursor))
    return (
        kind,
        _replace_constants(ast[1], values, cursor),
        _replace_constants(ast[2], values, cursor),
    )


def _collect_constants(ast: Node) -> list[float]:
    kind = ast[0]
    if kind == "const":
        return [float(ast[1])]
    if kind == "var":
        return []
    if kind in UNARY_OPERATORS:
        return _collect_constants(ast[1])
    return _collect_constants(ast[1]) + _collect_constants(ast[2])


def _affine_wrap(inner: Node, a: float, b: float) -> Node:
    return ("add", ("mul", ("const", float(a)), inner), ("const", float(b)))


@dataclass
class _Candidate:
    """A searched expression tree plus its analytic affine calibration.

    ``inner`` is the searched expression.  ``nodes``/``depth`` describe exactly
    that tree, which is what the pre-registered complexity limits constrain.
    The calibration coefficients ``(a, b)`` are fitted analytically and reported
    separately, mirroring how PySR reports fitted constants.
    """

    inner: Node
    a: float
    b: float
    score: float
    nodes: int
    depth: int

    @property
    def ast(self) -> Node:
        return _affine_wrap(self.inner, self.a, self.b)

    def key(self) -> str:
        return repr(self.inner)


class _ExpressionSearch:
    """Deterministic bounded search with an exact evaluation counter."""

    def __init__(self, spec: SymbolicSpec, limits: SymbolicLimits,
                 x: np.ndarray, y: np.ndarray, names: Sequence[str]) -> None:
        self.spec = spec
        self.limits = limits
        self.x = x
        self.y = y
        self.names = list(names)
        self.evaluations = 0
        self.registry: dict[int, _Candidate] = {}

    # -- scoring ---------------------------------------------------------
    def _score(self, inner: Node) -> _Candidate | None:
        if self.evaluations >= self.limits.eval_budget:
            return None
        self.evaluations += 1
        if node_count(inner) > self.limits.max_nodes or node_depth(inner) > self.limits.max_depth:
            return None
        try:
            raw = _evaluate(inner, self.x)
        except (FloatingPointError, ZeroDivisionError, OverflowError):
            return None
        if raw.shape != self.y.shape or not np.isfinite(raw).all():
            return None
        variance = float(np.var(raw))
        span = float(np.ptp(raw))
        magnitude = max(1.0, float(np.max(np.abs(raw))))
        # A degenerate (constant or numerically constant) expression carries no
        # feature information and must not enter the candidate registry.  The
        # relative span test is used because the floating-point variance of a
        # constant array is a tiny positive number, not exactly zero.
        if variance <= 0.0 or span <= 1e-12 * magnitude:
            return None
        design = np.column_stack([raw, np.ones_like(raw)])
        gram = design.T @ design
        try:
            solution = np.linalg.solve(gram, design.T @ self.y)
        except np.linalg.LinAlgError:
            return None
        a, b = float(solution[0]), float(solution[1])
        if not math.isfinite(a) or not math.isfinite(b):
            return None
        prediction = a * raw + b
        if not np.isfinite(prediction).all():
            return None
        candidate = _Candidate(
            inner=inner, a=a, b=b, score=float(wmape(self.y, prediction)),
            nodes=node_count(inner), depth=node_depth(inner),
        )
        best = self.registry.get(candidate.nodes)
        if best is None or candidate.score < best.score:
            self.registry[candidate.nodes] = candidate
        return candidate

    def register(self, inner: Node) -> _Candidate | None:
        """Score an externally supplied expression (used by the PySR backend)."""
        return self._score(inner)

    # -- search ----------------------------------------------------------
    def run(self) -> dict[str, Any]:
        base: list[Node] = [("var", index) for index in range(self.x.shape[1])]
        for value in self.limits.const_seeds:
            base.append(("const", float(value)))
        beam: list[_Candidate] = []
        for ast in base:
            candidate = self._score(ast)
            if candidate is not None:
                beam.append(candidate)
        beam.sort(key=lambda c: (c.score, c.nodes))
        beam = beam[: self.limits.beam_width]
        best_score = beam[0].score if beam else math.inf
        stale = 0
        levels_run = 0
        stop_reason = "depth_limit"
        for _level in range(1, self.limits.max_depth + 1):
            if self.evaluations >= self.limits.eval_budget:
                stop_reason = "budget_exhausted"
                break
            produced: list[_Candidate] = []
            for candidate in beam:
                for op in self.spec.operators:
                    if op not in UNARY_OPERATORS:
                        continue
                    if _contains(candidate.inner, NONLINEAR_UNARY):
                        continue
                    scored = self._score((op, candidate.inner))
                    if scored is not None:
                        produced.append(scored)
            binary_ops = [op for op in self.spec.operators if op in BINARY_OPERATORS]
            for index, left in enumerate(beam):
                for right in beam[index:]:
                    for op in binary_ops:
                        if op == "safe_ratio" and (
                            _contains(left.inner, frozenset({"safe_ratio"}))
                            or _contains(right.inner, frozenset({"safe_ratio"}))
                        ):
                            continue
                        scored = self._score((op, left.inner, right.inner))
                        if scored is not None:
                            produced.append(scored)
            levels_run = _level
            if not produced:
                stop_reason = "no_candidates"
                break
            combined = sorted(beam + produced, key=lambda c: (c.score, c.nodes))
            beam = combined[: self.limits.beam_width]
            if beam and beam[0].score < best_score - 1e-12:
                best_score = beam[0].score
                stale = 0
            else:
                stale += 1
                if stale >= self.limits.no_improve_rounds:
                    stop_reason = "converged"
                    break
            if self.evaluations >= self.limits.eval_budget:
                stop_reason = "budget_exhausted"
                break
        candidates = sorted(self.registry.values(), key=lambda c: (c.nodes, c.score))
        return {
            "candidates": candidates[: self.limits.max_candidates],
            "evaluations": int(self.evaluations),
            "eval_budget": int(self.limits.eval_budget),
            "levels_run": int(levels_run),
            "stop_reason": str(stop_reason),
            "n_distinct_complexities": int(len(self.registry)),
        }


class BoundedExpressionRegressor:
    """One bounded symbolic recipe fitted on a caller-supplied training part."""

    def __init__(
        self,
        recipe_id: str,
        *,
        limits: Mapping[str, Any] | None = None,
        n_inner_splits: int = 5,
        inner_seed: int = 42,
        backend: str = "pysr",
        pysr_settings: Any = None,
        root: Path | str = ".",
        allow_backend_fallback: bool = True,
    ) -> None:
        self.spec = SymbolicSpec(recipe_id)
        self.limits = SymbolicLimits(limits)
        self.n_inner_splits = int(n_inner_splits)
        self.inner_seed = int(inner_seed)
        self.recipe_id = self.spec.recipe_id
        if str(backend) not in {"pysr", "in_repo"}:
            raise ValueError(f"Unknown S backend: {backend!r}")
        self.backend = str(backend)
        self.pysr_settings = pysr_settings
        self.root = Path(root).resolve()
        self.allow_backend_fallback = bool(allow_backend_fallback)

    # -- design matrix ---------------------------------------------------
    def _design(self, frame: pd.DataFrame) -> np.ndarray:
        x = frame.loc[:, list(FEATURES)].to_numpy(dtype=np.float64)
        standardized = (x - self.means_) / self.stds_
        spout = np.zeros((len(frame), len(self.spout_to_index_) + 1), dtype=np.float64)
        for row, value in enumerate(frame["spout_no"].astype(int).tolist()):
            spout[row, self.spout_to_index_.get(int(value), 0)] = 1.0
        return np.ascontiguousarray(np.column_stack([standardized, spout]))

    def _fit_preprocessing(self, frame: pd.DataFrame) -> None:
        x = frame.loc[:, list(FEATURES)].to_numpy(dtype=np.float64)
        if not np.isfinite(x).all():
            raise ValueError("S line requires finite numerical features")
        self.means_ = x.mean(axis=0)
        self.stds_ = x.std(axis=0, ddof=0)
        self.stds_[np.isclose(self.stds_, 0.0)] = 1.0
        values = sorted({int(v) for v in frame["spout_no"].astype(int).tolist()})
        self.spout_to_index_ = {int(v): index + 1 for index, v in enumerate(values)}
        self.feature_names_ = [
            *[str(name) for name in FEATURES],
            *[f"spout_{value}" for value in values],
            "spout_unseen",
        ]

    # -- fit -------------------------------------------------------------
    def fit(
        self,
        frame: pd.DataFrame,
        target: str,
        *,
        train_config: Mapping[str, Any] | None = None,
    ) -> "BoundedExpressionRegressor":
        config = TrainConfig.from_mapping({**dict(train_config or {}), "loss": SYMBOLIC_LOSS})
        if str(config.loss) != SYMBOLIC_LOSS:
            raise ValueError("S line optimises an absolute-error objective")
        frame = frame.reset_index(drop=True)
        y_raw = np.asarray(frame[target], dtype=np.float64)
        if not np.isfinite(y_raw).all():
            raise ValueError("S line requires finite training targets")
        self.target_ = str(target)
        split = inner_uh_split(frame, n_splits=self.n_inner_splits, seed=self.inner_seed)
        u_index, h_index = split["u_index"], split["h_index"]
        if not len(u_index) or not len(h_index):
            raise ValueError("S line requires a nonempty U/H split")

        self._fit_preprocessing(frame)
        x_all = self._design(frame)
        self.scaler_ = TargetScaler.fit(y_raw)
        y_scaled = self.scaler_.transform(y_raw)

        x_u, y_u = x_all[u_index], y_scaled[u_index]
        x_h = x_all[h_index]
        y_h_raw = y_raw[h_index]

        with FitTimer() as timer:
            outcome = self._run_backend(x_u, y_u)
        search_seconds, search_memory = timer.seconds, timer.report()
        if not outcome["candidates"]:
            raise RuntimeError("S line search produced no finite candidate expression")

        # Selection happens on H only, in the original units, ties by complexity.
        selection: list[dict[str, Any]] = []
        for candidate in outcome["candidates"]:
            raw = candidate.a * _evaluate(candidate.inner, x_h) + candidate.b
            if not np.isfinite(raw).all():
                selection.append({
                    "expression": ast_to_string(candidate.inner, self.feature_names_),
                    "nodes": candidate.nodes,
                    "u_wmape": candidate.score, "h_wmape": None, "selected": False,
                    "note": "nonfinite_on_H",
                })
                continue
            predicted = self.scaler_.inverse(raw)
            h_wmape = float(wmape(y_h_raw, predicted))
            selection.append({
                "expression": ast_to_string(candidate.inner, self.feature_names_),
                "nodes": int(candidate.nodes),
                "u_wmape": float(candidate.score), "h_wmape": h_wmape,
                "selected": False, "note": "finite_on_H",
            })
        usable = [row for row in selection if row["h_wmape"] is not None]
        if not usable:
            raise RuntimeError("S line: every candidate was nonfinite on the validation part")
        chosen = min(usable, key=lambda row: (row["h_wmape"], row["nodes"]))
        for row in selection:
            row["selected"] = row is chosen
        selected_candidate = next(
            c for c in outcome["candidates"]
            if ast_to_string(c.inner, self.feature_names_) == chosen["expression"]
        )

        # Re-estimate every constant of the frozen structure on the complete
        # training part.  No new expression is invented here.
        with FitTimer() as timer:
            refined_ast, refine_meta = self._refine_constants(
                selected_candidate.ast, x_all, y_scaled
            )
        refit_seconds, refit_memory = timer.seconds, timer.report()

        self.ast_ = refined_ast
        self.expression_ = ast_to_string(refined_ast, self.feature_names_)
        self._check_finite(x_all, where="train")
        self.fit_outcome_ = TrainOutcome(
            requested={
                **config.requested(),
                "recipe": self.spec.as_dict(),
                "limits": self.limits.as_dict(),
                "target": str(target),
            },
            effective={
                "loss": SYMBOLIC_LOSS,
                "backend": str(outcome["backend"]),
                "searched_expression_evaluations": int(outcome["evaluations"]),
                "eval_budget": int(outcome["eval_budget"]),
                "budget_saturated": bool(
                    outcome.get("pysr", {}).get("budget_saturated")
                    if outcome["backend"] == "pysr"
                    else outcome["evaluations"] >= outcome["eval_budget"]
                ),
                "search_stop_reason": str(outcome["stop_reason"]),
                "fallback_used": bool(outcome.get("fallback_used", False)),
                "levels_run": int(outcome["levels_run"]),
                "n_candidates_kept": int(len(outcome["candidates"])),
                "n_distinct_complexities": int(outcome["n_distinct_complexities"]),
                # Complexity of the *searched expression tree*, which is what the
                # pre-registered 24-node / depth-5 limits constrain.  The affine
                # calibration head is reported separately.
                "selected_nodes": int(node_count(selected_candidate.inner)),
                "selected_depth": int(node_depth(selected_candidate.inner)),
                "model_nodes_including_calibration_head": int(node_count(refined_ast)),
                "model_depth_including_calibration_head": int(node_depth(refined_ast)),
                "affine_calibration": "prediction = b + a * expression",
                "calibration_coefficients": [
                    float(v) for v in _collect_constants(refined_ast)
                ],
                "n_constants_refit": int(len(_collect_constants(refined_ast))),
                "expression": self.expression_,
                "constant_refit": refine_meta,
            },
            stop_reason=str(outcome["stop_reason"]),
            best_epoch=0,
            stopped_epoch=0,
            best_validation_wmape=float(chosen["h_wmape"]),
            history=[],
            seconds=float(search_seconds + refit_seconds),
            peak_memory={"search": search_memory, "constant_refit": refit_memory},
            randomness={
                "search_seed": int(config.seed),
                "deterministic": True,
                "inner_split_seed": int(self.inner_seed),
                "note": "the in-repo search is deterministic and consumes no random draws",
            },
            fit_row_id_hash=fit_row_id_hash(frame["sample_id"].tolist()),
            fit_group_hash=group_hash(exclusion_group_keys(frame).tolist()),
            transform_hash=transform_hash({
                "target_scale": self.scaler_.metadata(),
                "means": self.means_.tolist(),
                "stds": self.stds_.tolist(),
                "spout_vocabulary": {str(k): int(v) for k, v in self.spout_to_index_.items()},
                "recipe": self.spec.as_dict(),
                "limits": self.limits.as_dict(),
            }),
            extra={
                "line": "S",
                "candidate_selection": selection,
                "pysr_backend": pysr_backend_report(),
                "backend_detail": {
                    k: v for k, v in outcome.items()
                    if k not in {"candidates"}
                },
                "mechanism_disclaimer": (
                    "Reported expression is a fitted formula, not a real blast-furnace "
                    "mechanism and not a recovered official generator."
                ),
            },
        )
        return self

    def _run_backend(self, x_u: np.ndarray, y_u: np.ndarray) -> dict[str, Any]:
        """Search with the frozen backend; PySR primary, in-repo on failure."""
        if self.backend == "pysr":
            payload = self._pysr_payload(x_u, y_u)
            if payload is not None:
                return payload
            if not self.allow_backend_fallback:
                raise RuntimeError("PySR backend failed and fallback is disabled")
        search = _ExpressionSearch(self.spec, self.limits, x_u, y_u, self.feature_names_)
        outcome = search.run()
        outcome.update({
            "backend": "in_repo_bounded_ast_search",
            "backends_attempted": ["pysr"] if self.backend == "pysr" else [],
            "fallback_used": bool(self.backend == "pysr"),
        })
        return outcome

    def _pysr_payload(self, x_u: np.ndarray, y_u: np.ndarray) -> dict[str, Any] | None:
        from dataclasses import replace as dataclass_replace

        from .v4_2_s_pysr import (
            PysrSettings,
            UnsupportedSympyExpression,
            run_pysr_search,
            sympy_text_to_ast,
        )

        settings = self.pysr_settings or PysrSettings.default(self.root)
        settings = dataclass_replace(
            settings,
            eval_budget=int(self.limits.eval_budget),
            maxsize=int(self.limits.max_nodes),
            maxdepth=int(self.limits.max_depth),
            seed=int(self.inner_seed),
        )
        self.pysr_probe_ = run_pysr_search(
            x_u, y_u, self.spec.operators, settings=settings, root=self.root
        )
        if not self.pysr_probe_.get("ok"):
            self.pysr_failure_ = {
                key: value for key, value in self.pysr_probe_.items() if key != "X"
            }
            return None
        scorer = _ExpressionSearch(self.spec, self.limits, x_u, y_u, self.feature_names_)
        accepted: list[dict[str, Any]] = []
        rejected: list[dict[str, Any]] = []
        for row in self.pysr_probe_.get("equations", []):
            text = str(row.get("equation", ""))
            try:
                ast = sympy_text_to_ast(text, int(x_u.shape[1]))
            except UnsupportedSympyExpression as exc:
                rejected.append({"equation": text, "reason": f"{type(exc).__name__}: {exc}"})
                continue
            except Exception as exc:  # noqa: BLE001
                rejected.append({"equation": text, "reason": f"{type(exc).__name__}: {exc}"})
                continue
            scored = scorer.register(ast)
            if scored is None:
                rejected.append({"equation": text, "reason": "rejected_by_complexity_or_finiteness"})
                continue
            accepted.append({
                "equation": text,
                "pysr_complexity": int(row.get("complexity", 0)),
                "pysr_loss": float(row.get("loss", float("nan"))),
                "v42_nodes": int(node_count(ast)),
                "v42_depth": int(node_depth(ast)),
                "calibrated_u_wmape": float(scored.score),
            })
        if not accepted:
            self.pysr_failure_ = {
                "status": "no_convertible_equations",
                "rejected": rejected[:20],
                "n_equations": int(self.pysr_probe_.get("n_equations", 0)),
            }
            return None
        candidates = sorted(scorer.registry.values(), key=lambda c: (c.nodes, c.score))
        return {
            "candidates": candidates[: self.limits.max_candidates],
            "evaluations": int(scorer.evaluations),
            "eval_budget": int(self.limits.eval_budget),
            "levels_run": 0,
            "stop_reason": "pysr_hall_of_fame_under_exact_max_evals_budget",
            "n_distinct_complexities": int(len(scorer.registry)),
            "backend": "pysr",
            "backends_attempted": ["pysr"],
            "fallback_used": False,
            "pysr": {
                "version": self.pysr_probe_.get("pysr_version"),
                "seconds": self.pysr_probe_.get("seconds"),
                "adapter_seconds": self.pysr_probe_.get("adapter_seconds"),
                "n_equations": int(self.pysr_probe_.get("n_equations", 0)),
                "effective_parameters": self.pysr_probe_.get("effective"),
                "settings": self.pysr_probe_.get("settings"),
                "accepted": accepted,
                "rejected": rejected[:20],
                "budget_saturated": True,
            },
        }

    def _refine_constants(
        self, ast: Node, x: np.ndarray, y_scaled: np.ndarray
    ) -> tuple[Node, dict[str, Any]]:
        initial = np.asarray(_collect_constants(ast), dtype=np.float64)
        if not len(initial):
            return ast, {"attempted": False, "reason": "structure_has_no_constants"}
        try:
            from scipy.optimize import least_squares
        except Exception:  # noqa: BLE001
            return ast, {"attempted": False, "reason": "scipy_unavailable"}

        bound = float(self.limits.constant_bound)

        def residual(values: np.ndarray) -> np.ndarray:
            candidate = _replace_constants(ast, values, [0])
            output = _evaluate(candidate, x)
            if not np.isfinite(output).all():
                return np.full(x.shape[0], 1e12, dtype=np.float64)
            return output - y_scaled

        try:
            result = least_squares(
                residual,
                np.clip(initial, -bound, bound),
                bounds=(-bound, bound),
                max_nfev=int(self.limits.constant_refit_max_nfev),
            )
            refined = _replace_constants(ast, np.asarray(result.x), [0])
            output = _evaluate(refined, x)
            if not np.isfinite(output).all():
                raise ValueError("nonfinite constant-refit result")
            return refined, {
                "attempted": True,
                "status": int(result.status),
                "nfev": int(result.nfev),
                "cost": float(result.cost),
                "max_abs_constant": float(np.abs(np.asarray(result.x)).max()),
                "initial_constants": [float(v) for v in initial],
                "refined_constants": [float(v) for v in np.asarray(result.x)],
            }
        except Exception as exc:  # noqa: BLE001
            return ast, {"attempted": True, "failed": True, "error": f"{type(exc).__name__}: {exc}"}

    def _check_finite(self, x: np.ndarray, *, where: str) -> np.ndarray:
        output = _evaluate(self.ast_, x)
        if not np.isfinite(output).all():
            raise ValueError(f"S line produced a nonfinite expression output on {where}")
        return output

    def predict(self, frame: pd.DataFrame) -> np.ndarray:
        if not hasattr(self, "ast_"):
            raise RuntimeError("BoundedExpressionRegressor must be fitted before prediction")
        frame = frame.reset_index(drop=True)
        x = self._design(frame)
        raw = self._check_finite(x, where="query")
        # Only the globally frozen non-negative output handling is inherited.
        result = np.maximum(self.scaler_.inverse(raw), 0.0)
        if result.shape != (len(frame),) or not np.isfinite(result).all():
            raise ValueError("Invalid S-line prediction")
        return result.astype(float, copy=False)

    # -- export ----------------------------------------------------------
    def to_numpy_source(self) -> str:
        """Self-contained NumPy translator of the fitted expression."""
        if not hasattr(self, "ast_"):
            raise RuntimeError("Fit before exporting")
        body = self._ast_to_source(self.ast_, indent="    ")
        means = ", ".join(repr(float(v)) for v in self.means_.tolist())
        stds = ", ".join(repr(float(v)) for v in self.stds_.tolist())
        vocabulary = json.dumps({str(k): int(v) for k, v in self.spout_to_index_.items()})
        return (
            "import numpy as np\n\n"
            "MEANS = np.asarray([%s], dtype=np.float64)\n"
            "STDS = np.asarray([%s], dtype=np.float64)\n"
            "SPOUT_TO_INDEX = %s\n"
            "SCALE = %r\n\n"
            "def predict(numeric, spout):\n"
            "    numeric = np.asarray(numeric, dtype=np.float64)\n"
            "    spout = np.asarray(spout, dtype=np.int64).reshape(-1)\n"
            "    if numeric.ndim != 2 or numeric.shape[1] != MEANS.shape[0]:\n"
            "        raise ValueError('unexpected numeric shape')\n"
            "    if numeric.shape[0] != spout.shape[0]:\n"
            "        raise ValueError('numeric/spout row mismatch')\n"
            "    x = (numeric - MEANS) / STDS\n"
            "    n = numeric.shape[0]\n"
            "    spout_block = np.zeros((n, len(SPOUT_TO_INDEX) + 1), dtype=np.float64)\n"
            "    for i, value in enumerate(spout.tolist()):\n"
            "        spout_block[i, SPOUT_TO_INDEX.get(str(int(value)), 0)] = 1.0\n"
            "    x = np.column_stack([x, spout_block])\n"
            "%s\n"
            "    out = np.asarray(out, dtype=np.float64)\n"
            "    if not np.isfinite(out).all():\n"
            "        raise ValueError('nonfinite expression output')\n"
            "    return np.maximum(out * SCALE, 0.0)\n"
        ) % (means, stds, vocabulary, float(self.scaler_.scale), body)

    def _ast_to_source(self, ast: Node, indent: str = "    ") -> str:
        """Emit single-assignment NumPy statements for one AST."""
        lines: list[str] = []
        counter = [0]

        def emit(node: Node) -> str:
            kind = node[0]
            name = f"t{counter[0]}"
            counter[0] += 1
            if kind == "var":
                lines.append(f"{indent}{name} = x[:, {int(node[1])}]")
            elif kind == "const":
                lines.append(
                    f"{indent}{name} = np.full(x.shape[0], {float(node[1])!r}, dtype=np.float64)"
                )
            elif kind in {"add", "sub", "mul"}:
                left = emit(node[1])
                right = emit(node[2])
                operator = {"add": "+", "sub": "-", "mul": "*"}[kind]
                lines.append(f"{indent}{name} = {left} {operator} {right}")
            elif kind == "safe_ratio":
                left = emit(node[1])
                right = emit(node[2])
                lines.append(f"{indent}{name} = {left} / (1.0 + {right} * {right})")
            elif kind == "tanh":
                lines.append(f"{indent}{name} = np.tanh({emit(node[1])})")
            elif kind == "log1p_abs":
                lines.append(f"{indent}{name} = np.log1p(np.abs({emit(node[1])}))")
            else:
                raise ValueError(f"Unexpected node in export: {kind!r}")
            return name

        root = emit(ast)
        lines.append(f"{indent}out = {root}")
        return "\n".join(lines)

    def exported_predict(self, numeric: np.ndarray, spout: np.ndarray) -> np.ndarray:
        """Run the exported NumPy translator in-process (backend/export parity)."""
        source = self.to_numpy_source()
        namespace: dict[str, Any] = {}
        exec(compile(source, "<v4_2_symbolic_export>", "exec"), namespace)  # noqa: S102
        return np.asarray(namespace["predict"](numeric, spout), dtype=np.float64)

    # -- backend capability ---------------------------------------------
    def backend_report(self) -> dict[str, Any]:
        return {
            "selected_backend": "in_repo_bounded_ast_search",
            "exact_evaluation_budget": True,
            "budget": int(self.limits.eval_budget),
            "pysr": pysr_backend_report(),
        }


def pysr_backend_report() -> dict[str, Any]:
    """Report whether an installed PySR backend can control an exact budget."""
    try:
        import inspect

        import pysr  # type: ignore
    except Exception as exc:  # noqa: BLE001
        return {
            "installed": False,
            "error": f"{type(exc).__name__}: {exc}",
            "budget_controllable": False,
            "used_for_search": False,
        }
    parameters = list(inspect.signature(pysr.PySRRegressor.__init__).parameters)
    budget_like = [
        name for name in parameters
        if any(token in name.lower() for token in ("eval", "iteration", "population", "cycle"))
    ]
    exact = [name for name in parameters if name in {"max_evals", "n_evals"}]
    return {
        "installed": True,
        "version": str(getattr(pysr, "__version__", "unknown")),
        "budget_like_parameters": budget_like,
        "exact_budget_parameters": exact,
        "budget_controllable": bool(exact),
        "used_for_search": False,
        "reason": (
            "PySR is only used when an exact evaluation budget is both accepted and "
            "reported by the installed backend; otherwise the in-repo bounded search "
            "is the frozen backend for this round."
        ),
    }
